source "https://rubygems.org"

gem "jekyll", "~> 4.0.0"
gem "jekyll-theme-cayman"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows compatibility
platforms :mingw, :x64_mingw, :mswin do
  gem "tzinfo", ">= 1"
  gem "tzinfo-data"
end

# Webrick for Ruby 3.0+
gem "webrick", "~> 1.7"
